import type { LucideIcon, LucideProps } from "lucide-react";
import {
  Award,
  BadgeCheck,
  BatteryCharging,
  BatteryFull,
  Briefcase,
  BedDouble,
  Bluetooth,
  BookOpen,
  Building2,
  CalendarRange,
  CircleHelp,
  Clock,
  CookingPot,
  CreditCard,
  Droplets,
  FileText,
  Flag,
  Flame,
  Gem,
  Globe,
  Handshake,
  Headphones,
  Headset,
  House,
  Images,
  Landmark,
  Layers,
  LayoutGrid,
  Leaf,
  Lightbulb,
  Luggage,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MessageSquareQuote,
  Mic,
  Monitor,
  Newspaper,
  Package,
  PencilRuler,
  Phone,
  Pill,
  Plane,
  Printer,
  PrinterCheck,
  Receipt,
  RefreshCcw,
  RotateCcw,
  Ruler,
  Scale,
  ScanSearch,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  SmartphoneCharging,
  Stamp,
  Truck,
  Undo2,
  Upload,
  Wallet,
  Zap,
} from "lucide-react";

/**
 * Icons that admin data may name (menus, categories, trust items, values). Only these are bundled; an unknown name
 * renders the fallback, so a typo in admin never breaks a page.
 */
const ICONS: Record<string, LucideIcon> = {
  award: Award,
  "badge-check": BadgeCheck,
  "battery-charging": BatteryCharging,
  "battery-full": BatteryFull,
  "bed-double": BedDouble,
  bluetooth: Bluetooth,
  "book-open": BookOpen,
  briefcase: Briefcase,
  "building-2": Building2,
  "calendar-range": CalendarRange,
  "circle-help": CircleHelp,
  clock: Clock,
  "cooking-pot": CookingPot,
  "credit-card": CreditCard,
  droplets: Droplets,
  "file-text": FileText,
  flag: Flag,
  flame: Flame,
  gem: Gem,
  globe: Globe,
  handshake: Handshake,
  headphones: Headphones,
  headset: Headset,
  house: House,
  images: Images,
  landmark: Landmark,
  layers: Layers,
  "layout-grid": LayoutGrid,
  leaf: Leaf,
  lightbulb: Lightbulb,
  luggage: Luggage,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  "message-square-quote": MessageSquareQuote,
  mic: Mic,
  monitor: Monitor,
  newspaper: Newspaper,
  package: Package,
  "pencil-ruler": PencilRuler,
  phone: Phone,
  pill: Pill,
  plane: Plane,
  printer: Printer,
  "printer-check": PrinterCheck,
  receipt: Receipt,
  "refresh-ccw": RefreshCcw,
  "rotate-ccw": RotateCcw,
  ruler: Ruler,
  scale: Scale,
  "scan-search": ScanSearch,
  "shield-check": ShieldCheck,
  ship: Ship,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "smartphone-charging": SmartphoneCharging,
  stamp: Stamp,
  truck: Truck,
  "undo-2": Undo2,
  upload: Upload,
  wallet: Wallet,
  zap: Zap,
};

type MenuIconProps = LucideProps & {
  /** Lucide icon name from the data layer, e.g. "book-open". */
  name?: string;
};

/** Renders a data-named Lucide icon (decorative: labels carry the meaning). */
function MenuIcon({ name, ...props }: MenuIconProps) {
  const Icon = (name ? ICONS[name] : undefined) ?? LayoutGrid;
  return <Icon aria-hidden="true" focusable="false" strokeWidth={1.75} {...props} />;
}

export { MenuIcon, ICONS as MENU_ICONS };
